### ISSUE TITLE
Allow the user to add a transaction

### ISSUE THREAD

**Issue by rnjohnson18** [CodePathGroupOne/BudgetApp#11]
- [x] Add a button to allow the user to add a transaction to their budget
- [x] user should be able to add a transaction with a pre-defined hash tag.
- [x] Let the user set a title, amount, bank account, and other details about their transaction
- [x] User should be able to cancel saving the transaction
- [x] Let the user select a budget hashtag to save the transaction to

**Optional Nice-to-have Stories**
- [ ] User can search transactions based on hashtags or text
- [ ] User can enter recurring transactions automatically that applies to a user defined frequency (weekly, biweekly or monthly) and also a user defined duration. These transactions could include utilities, tuitions etc

**Comment by 50417** [comment]
Adding transactions to the parse is completed with 814aecba17ff3983af52c77bf1eccef3e9d6eb9d
TODO: 
* Populate with actual hashtags and insert the object instead of dummy hashtag text.  
* Show recent transactions
