### ISSUE TITLE
User can set up a monthly budget

### ISSUE THREAD

**Issue by rnjohnson18** [CodePathGroupOne/BudgetApp#12]
- [x] User should be able to add a budget, which is displayed as a hashtag
- [x] User should be able to allocate an amount of money toward that budget
- [x] User can edit their monthly budget to be applied to the current month or following months.

**Comment by 50417** [comment]
Displaying predefined hashtags fetched from parse server is done with 9f37b46cdb4d2f72855bdca6442b1198d2ad4141 .

TODO: 
* Get the budget from UI and update it into parse table 
* Also add a update button and month of the budget

**Comment by 50417** [comment]
Previous comment TODO list is completed in e9a8cc3bd2befcdaa44917be32f77f44572c767d

TODO: 
* Get current budget if already exists and populate to the UI
* Update the budget if user changes any values in the hashtags 
*

**Comment by 50417** [comment]
Previous comment has been completed with baf1de65c2736e0166b6d45cedb7a89a6910ccdc and bce96ad16a2fdb75654ea490dc6e605c374c7246

TODO : 
* Make the synchronous query efficient by doing sanity checks. 
* Update budget has a bug where any hashtag that is not interacted with default to zero.
